/**
 * Api Notifier
 * Notification system for eduroam network
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Notification } from './notification';

export interface IdentifierNotification { 
    delivered: boolean;
    notification: Notification;
}